version: "3"

x-compose_env: &compose_env
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    #entrypoint: ["bash", 'bin/entrypoint']
    environment:
      <<: *compose_env
      AIRTABLE_API_KEY: $AIRTABLE_API_KEY
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
  db:
    image: postgres:13
    environment:
      <<: *compose_env
      POSTGRES_USER: postgres
      POSTGRES_DB: dea_register_frontend
